### ISSUE TITLE
Inclusión de vuestro proyecto entre las implementaciones de Heritage in...

### ISSUE THREAD

**Issue by espinr** [coral2742/Quick-app#1]
Hola @coral2742 ,

Ante todo, muchas gracias por participar en el hackathon del W3C el pasado 9 de marzo. Habéis hecho un gran trabajo en sólo 90 minutos. Como os prometimos, nos gustaría promocionar vuestro trabajo y listarlo entre las implementaciones de referencia de [heritagein.info](https://heritagein.info). 

Si deseáis refinar el ejemplo, cambiando algunos de los textos descriptivos para presentar a vuestro equipo y el contexto del desarrollo del mismo, podéis hacerlo en vuestro propio repositorio y avisarme cuando lo tengáis listo (aquí mismo) o simplemente hacer un pull request directamente al [repositorio principal](https://github.com/ow2-quick-app-initiative/poi-quick-app-implementations). Así podemos reconocer vuestro gran trabajo con la atribución correspondiente, además de servir de inspiración a otros.

Un saludo!

**Comment by coral2742** [comment]
Buenas tardes! Gracias a vosotros por organizar y ofrecernos la oportunidad de participar en este evento. No habría ningún problema en que se promocione nuestro proyecto, aunque nos gustaría hacer algunas modificaciones en los textos descriptivos y algunos detalles. Actualizaremos los cambios como nos indicáis y les avisaremos en cuanto esté listo. Un saludo!

**Comment by coral2742** [comment]
Buenas noches, estos días actualizamos el repositorio con nuevos sitios y pequeños detalles y consideramos que ya estaría listo. Gracias por tenernos en cuenta, un saludo.

**Comment by espinr** [comment]
He actualizado el fichero de las implementaciones y ya lista vuestro ejemplo. 
https://heritagein.info/greenday/ 

He enlazado el fichero data.json desde vuestro repositorio, así que cualquier cambio se verá reflejado. Seguimos en contacto. Muchas gracias.
